# Reference: https://github.com/marketplace/actions/setup-node-js-environment 

name: Truffle Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm --version
    - name: Create .env file
      run: echo "${{ secrets.DOT_ENV }}";echo "${{ secrets.DOT_ENV }}" > .env  
    - name: Install Truffle
      run: npm install truffle -g
    - name: Run Truffle Test  
      run: truffle test


